apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-frontend
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
    app.kubernetes.io/component: frontend
